### ISSUE TITLE
only launch primal feasibility solves for primal infeasiblily

### ISSUE THREAD

**Issue by whoburg** [convexengineering/gpkit#842] opened 2016-09-06 02:45 UTC
@mayork has some SP models that are dual infeasible. When solved, mosek correctly identifies the GP approximation of these models as dual infeasible, but then GPkit forms a primal feasibility problem (which is useless). For a _dual_ infeasible model, we should directly raise an error.

It's tempting to automatically form a BoundedConstraintSet version here, but I think that should be done by GPkit always or never -- not just for the special case of an SP.

**Comment by bqpd** [comment] 2016-09-06 16:59
but that's orthogonal to this issue, isn't it...

Your reccomended solution will require us to be more consistent about solver status messages, which will be a good thing. Among other things, it'll allow us to define primal/dual infeasibility in the error message raised by `.solve`

**Comment by whoburg** [comment] 2016-09-08 01:37
sounds good. And I like your idea too -- I've been thinking about calling it `Model.debug()`.
The error messages raised by solving dual or primal infeasible Models would include a suggestion to try calling `debug()`.

Of course this is a bit dangerous because users may expect it to fix everything, which it won't.

**Comment by bqpd** [comment] 2016-09-08 02:16
I quite like calling it `debug`, though.

**Comment by bqpd** [comment] 2016-09-08 02:17
In the new feasibility model pr I call it relaxing instead of slacking :p

**Comment by bqpd** [comment] 2017-11-03 00:21
duplicate of #769

**Closed by bqpd** 2017-11-03 00:21 UTC
