### ISSUE TITLE
Vectorize doesn't work for matrix vector variable

### ISSUE THREAD

**Issue by mjburton11** [convexengineering/gpkit#1292] opened 2018-03-29 15:11 UTC
I currently can't do the following: 

```python
with Vectorize([1, 3]):
    x = Variable("x")
```

but I can do
```python
x = VectorVariable([1, 3], "x")
```

Error: 

```python
/Users/mjburton11/MIT/GPKIT/gpkit/gpkit/nomials/variables.pyc in __new__(cls, shape, *args, **descr)
    159 
    160         arraykey = VarKey(**descr)
--> 161         vl = np.empty(shape, dtype="object")
    162         it = np.nditer(vl, flags=['multi_index', 'refs_ok'])
    163         while not it.finished:

TypeError: 'list' object cannot be interpreted as an index
```

**Comment by mjburton11** [comment] 2018-03-29 15:18
Although I can do: 

```python
with Vectorize(1):
    with Vectorize(3):
        x = Variable("x")
```

**Comment by bqpd** [comment] 2018-03-29 15:41
Yup, vectorize has to be nested at present. I think this will stay part of the requirement, since one thing about the way vectorized has to work is that the innermost dimension is the leftmost, so that calls referencing vectors work (e.g., w_tip = w[-1] in the beam, or see the test below) work even inside a vectorization. In your example above this means that your last x is equivalent to `x = VectorVariable([3, 1], "x")`.

If vectorization accepted a list as input I think this would only be more confusing; @mjburton11 what do you think?

```python
class TestVectorize(unittest.TestCase):
    """TestCase for gpkit.vectorize"""

    def test_shapes(self):
        with gpkit.Vectorize(3):
            with gpkit.Vectorize(5):
                y = gpkit.Variable("y")
                x = gpkit.VectorVariable(2, "x")
            z = gpkit.VectorVariable(7, "z")

        self.assertEqual(y.shape, (5, 3))
        self.assertEqual(x.shape, (2, 5, 3))
        self.assertEqual(z.shape, (7, 3))
```

**Comment by mjburton11** [comment] 2018-03-29 15:43
Yeah that's fine with me.  I just didn't understand the nested Vectorization until I played with it a bit more.

**Comment by mjburton11** [comment] 2018-03-29 15:43
But possible a related issue can be found in `solar` commit 295051844c029d0b71bd0d33eb719c0069351cbb

```python
/Users/mjburton11/MIT/GPKIT/gpkit/gpkit/nomials/variables.pyc in newlinkedfn(c)
    193     def newlinkedfn(c):
    194         "Linked function that pulls out a particular index"
--> 195         return np.array(linkedfn(c))[i]
    196     return newlinkedfn
    197 

IndexError: too many indices for array
```

**Comment by bqpd** [comment] 2018-03-29 15:45
Hmm! That might also be related to the new automatic differentiation of linked variables...have you pip installed `ad` yet to get that?

**Comment by mjburton11** [comment] 2018-03-29 15:45
mmmm no

**Comment by mjburton11** [comment] 2018-03-29 15:45
What are you referring to?

**Comment by mjburton11** [comment] 2018-03-29 15:46
I did pip install ad but got the same error? Do I need to reinstall gpkit?

**Comment by bqpd** [comment] 2018-03-29 15:49
are you on the latest master? It should have started giving you messages about the variables it can't auto differentiate

**Comment by mjburton11** [comment] 2018-03-29 15:50
Yeah I am on the latest master

**Comment by mjburton11** [comment] 2018-03-29 15:51
were you able to reproduce the error?

**Comment by bqpd** [comment] 2018-03-30 15:24
I believe the problem is that your linked function is outputting a 1D array

**Comment by mjburton11** [comment] 2018-03-30 15:25
oh hmmm

**Comment by bqpd** [comment] 2018-03-30 15:26
yeah, line 534 in solar.py, you return a list and not a matrix

**Comment by bqpd** [comment] 2018-03-30 15:26
to debug I stuck `        print "rho", rho` on line 548 of solar.py and `        print i, np.array(linkedfn(c))` on line 195 of gpkit/nomials/variables.py

**Comment by bqpd** [comment] 2018-03-30 15:27
the latter shows that it's happily using a tuple idx

**Comment by bqpd** [comment] 2018-03-30 15:27
Closing this issue as it should probably now be in solar...

**Comment by mjburton11** [comment] 2018-03-30 15:28
Ok sorry...

**Closed by bqpd** 2018-03-30 15:27 UTC

**Comment by mjburton11** [comment] 2018-03-30 15:29
Although, now I see 
```
Couldn't auto-differentiate linked variable rho_Mission/Climb_(0, 2).
Couldn't auto-differentiate linked variable cosminus1_Mission/FlightSegment/GustL_(9,).
Couldn't auto-differentiate linked variable cosminus1_Mission/FlightSegment/GustL_(3,).
Couldn't auto-differentiate linked variable rho_Mission/Climb_(0, 4).
Beginning signomial solve.
```

**Comment by bqpd** [comment] 2018-03-30 15:30
Heh no worries! Let me know if you come up with a cleaner error message I could raise!

Haha, yeah. If make sure everything you return is an ad.adnumber, you can take advantage of the auto-diff! Otherwise you'll continue to see sensitivities to `rho` and `cosminus1`

(to get autodiff working for cosminus1, you need `from ad.math import cos` and then wrap the initial epsilon in an ad.adnumber)

**Comment by mjburton11** [comment] 2018-03-30 15:31
ohhh ok. Are there adlists?

**Comment by mjburton11** [comment] 2018-03-30 15:31
or adarrays?

**Comment by mjburton11** [comment] 2018-03-30 15:35
When I made it an adnumber I got this error: 

```python 
ValueError: substitution {rho_Mission/Climb_(0, 2): ad(0.365178107808)} with value type <class 'ad.ADV'> is not allowed in .substitutions; such substitutions must be done by using .subinplace().
```

**Comment by bqpd** [comment] 2018-03-30 16:09
You want to make the return value an adnumber, not the substitution...

**Comment by bqpd** [comment] 2018-03-30 16:09
ad.adnumber(array or list) should work fine!

**Comment by bqpd** [comment] 2018-03-30 16:11
But uh you only want to create new adnumbers of constants, like the epsilon that starts the return of cosminus1; all your other values should just naturally be adnumbers, because the constants dictionary that's passed in to linked variables is adnumbers, and they track their derivatives throughout the calculations. Every time you make a new adnumber it makes a new variable, which, since it's not in constants, will not be present in the sensitivities table

**Comment by bqpd** [comment] 2018-03-30 16:11
I'll fix cosminus1 to demonstrate

**Comment by bqpd** [comment] 2018-03-30 16:13
ad documentation: https://pypi.python.org/pypi/ad/1.2.3

**Comment by bqpd** [comment] 2018-03-30 16:16
@mjburton11, see https://github.com/convexengineering/gplibrary/pull/158
