### ISSUE TITLE
values clobbering new substitutions because of constraint ordering choice

### ISSUE THREAD

**Issue by mjburton11** [convexengineering/gpkit#1175] opened 2017-10-13 21:35 UTC
Looking at commit convexengineering/solar@e99e9e7428911d6f769684d1d7cc0b38939283b0 in solar, solving `solar.py` and convexengineering/library@c6da5c00e87137a7af7e32dcff2dc141e612eea5 in gpkitmodels.  I am subbing in tau in HTail.  

```python 
class HorizontalTail(AeroSurf):
    "horizontal tail model"
    flight_model = TailAero
    sparModel = None

    def setup(self, N=3, lam=0.8):
        self.ascs = AeroSurf.setup(self, N, lam)
        self.planform.substitutions.update({"AR": 4, "\\tau": 0.08})
```
But when I solve the model I get this:
```python
In [2]: sol("\\tau")
Out[2]: 
{\tau_Mission/Aircraft/Empennage/HorizontalTail/Planform: 0.115,
 \tau_Mission/Aircraft/Empennage/VerticalTail/Planform.1: 0.115,
 \tau_Mission/Aircraft/AeroSurf/Planform.2: 0.115}

In [3]: M.substitutions["\\tau_Mission/Aircraft/Empennage/VerticalTail/Planform.
   ...: 1"]
Out[3]: 0.115

In [4]: sol("AR")
Out[4]: 
{AR_Mission/Aircraft/Empennage/HorizontalTail/Planform: 4,
 AR_Mission/Aircraft/Empennage/VerticalTail/Planform.1: 3.7197870897370509,
 AR_Mission/Aircraft/AeroSurf/Planform.2: 26.66897625889953}
```
Pretty weird that `AR` got changed, but not `tau`

**Comment by bqpd** [comment] 2017-10-13 23:13
the problem is in https://github.com/convexengineering/solar/blob/e0d1f51459d945b3c71ff23012c9001c358168bf/solar/solar.py#L320 ; because `self.mission` contains `\\tau` (in the performance models), but no substitutions for it, it pulls the value out of the variable. Because it comes second in the list, its substitutions replace those of `self.solar`

In the short term this can be fixed by reordering them: `return self.mission, self.solar`

In the long term this requires a different approach to substitutions.

**Comment by mjburton11** [comment] 2017-10-14 15:52
Interesting.  The reordering worked.  Feels like this shouldn't be a problem.  Maybe a design discussion question??

**Closed** 2018-03-21 20:30 UTC
Labels: design discussion
