### ISSUE TITLE
Mixed-integer geometric programming

### ISSUE THREAD

**Issue by whoburg** [convexengineering/gpkit#414] opened 2015-10-01 14:56 UTC
To support #413, how hard would it be to add a way of specifying integer variables?

For now, I don't think we want to get be in the business of solving MIGP problems, so the needed functionality is just using GPkit to get from a symbolic description to dumping out the solver format (c, A, map, and some way of encoding which variables are integer, probably borrowing the formatting conventions from AMPL or one of the MILP solvers).

**Comment by bqpd** [comment] 2015-10-21 02:13
Super easy! :dancer: 

``python
x = Variable("x", "m", integer=True)
``

**Comment by whoburg** [comment] 2015-10-21 02:16
Would need to hook this into a way of dumping out c, A, map, etc -- I'm assuming we don't want to be in the business of writing MIGP solvers, so we need to start looking at what interfaces are out there (if any)

**Comment by bqpd** [comment] 2015-10-21 02:18
Most solvers accept a list of which variables are integers as an additional arg, that I've seen.

**Comment by whoburg** [comment] 2015-10-24 14:31
I haven't read the paper yet, and the news article is a little bit painful to read, but this work might have interesting (good) consequences for solving MIGP's.

**Comment by whoburg** [comment] 2016-03-21 17:37
Here's a tiny example for working out how the GPkit interface might work:
http://users.isy.liu.se/johanl/yalmip/pmwiki.php?n=Tutorials.GeometricProgramming

Also, mlubin says:
"On the modeling side, I'd say the most natural way to write down an MIGP is to take the GP in the untransformed variables and add constraints that certain variables take values in given finite sets (e.g., x_i \in {2.6, 4.6, 50.0}). Then it will be our job (i.e., as the solver) to take that and formulate it as a mixed-integer convex problem in the log space. So MIGP is a bit of a misnomer since modelers wouldn't necessarily write down any integer constraints."

**Comment by bqpd** [comment] 2016-03-21 17:47
Haven't read the link yet, but the finite set concept makes a lot of sense.
It could easily be handled like substitutions if per-varkey declaration is
not sufficient.

**Comment by 1ozturkbe** [comment] 2020-01-16 13:00
I was about going to make an issue and decided to search the issues first. For some work I'm doing using machine learning for design this is going to be important, and mosek supports mixed-integer conic programs which will make everything easier hopefully. 

Also makes sense to have a set-based system where we pass it as substitutions. Will see what I can do.

**Comment by bqpd** [comment] 2020-02-04 23:36
@rileyjmurray, thanks so much for your help on integrating the mosek 9 conic solver? now that that's merged, how would you recommend doing mixed-integer geometric programming? the biggest problem I see is that the variables we want to constrain to integers (or to discrete sets) are not directly represented as variables in the conic formulation.

**Comment by erling-d-andersen** [comment] 2020-02-05 10:22
A perhaps naive comment.

I do not see how to do the mixed integer in log space. 

My line of thinking is that only variables that in the original space that are not integer constrained is moved to log space. And then you hope that the resulting problem is mixed integer convex.

I.e. if you can not do mixed integer problems if you want to think of pure GP problems.

**Comment by 1ozturkbe** [comment] 2020-02-05 14:44
@erling-d-andersen the idea was to define a finite integer set for each variable in the original space (eg. x in [1,2,4] as opposed to x in Z+), then do a map on the optimizer API side from an integer variable in logspace to the log of each item in the set. This should be possible right?

**Comment by rileyjmurray** [comment] 2020-02-05 19:10
I can think of three approaches to mixed integer geometric programming. Each of these approaches assumes that posynomial variables ``x`` can only take on integer values ``>= 1`` (i.e. assiging a posynomial variable zero isn't allowed). The first two approaches require the set of integer values to be finite, and known ahead of time.

In the discussion below I use cvxpy syntax to describe convex programming models in high-level terms. I also use python >= 3.5's  ``@`` operator for matrix multiplication.

## Approach 1: constrain a posynomial variable to take value in a finite set.

Let ``a`` be a sorted array (increasing order) of positive values. We want to constrain a posynomial variable ``x`` to take on a value ``a[i]``.  From the perspective of the convex formulation, we need to enforce constraints on ``y`` where ``y = log(x)``. Of course, ``x`` takes on a desired value as long as ``y`` takes on a value in ``L = np.log(a)``. If by some fluke ``L`` consisted of only integer values, then we could easily pass this to a convex solver like MOSEK. In reality, ``L`` will not contain integer values. So the problem reduces to this: how can we constrain a variable ``y`` in a mixed-integer convex program to take values in a finite non-integer set? I can think of two ways to do this.

The naive way is to introduce an indicator variable for each value in ``L``, i.e. ``z = Variable(shape=(L.size), boolean=True)``, then introduce constraints ``y == L @  z`` and ``sum(z) == 1``. This causes ``y`` to take a value in ``L``, and in turn causes ``x`` to take a value in ``a``. The problem with this approach is that the LP-relaxations encountered during branch and bound will produce little useful information. So a MIP solver will probably converge very slowly.

The better way to do this is to assign ``y`` a value based on an incremental sum. Set ``d = np.diff(L)`` and ``z = Variable(shape=(d.size,), boolean=True)``. Introduce the following constraints:
```
logic_cons = [z[i+1] <= z[i] for i in range(z.size-1)] + [sum(z) <= 1]
all_cons = logic_cons + [y == L[0] + d @ z]
```
The constraints in ``logic_cons`` together with 0/1 constraints on ``z`` ensure that ``z`` is always a vector of the form ``[1,...,1,0,...,0]`` -- i.e. consecutive ones, then consecutive zeros. The constraint ``y == L[0] + d @ z`` ensures that ``y`` takes a value in ``L``. NOTE: this approach required ``a`` (and hence ``L``) to be sorted, while the first approach didn't.

## Approach 2: transform the problem to a signomial program.

A constraint that ``x`` takes a value in ``a`` can be written as ``expr = np.prod([x[i] - a[i] for i in range(a.size)]`` and ``expr == 0``. From here you could either apply any method for signomial programming. For example, SGP could probably get you locally optimal solutions (as long as it doesn't return a value code). You could also take a convex relaxation approach to the SP, such as a SAGE relaxation.

For an explicit example of a simple dual-SAGE relaxation, refer to Equation (9) in Section 3.2 of [this paper](https://arxiv.org/pdf/1907.00814.pdf). For better bounds, you could apply integrality constraints to certain entries of the "moment vector" ``v``.  In fact, if you used integrality constraints on ``v``, the moment-vector equality constraints ``Phi @ v == 0`` could be dropped (although I doubt there is much benefit in doing so). If you don't add integrality constraints on ``v``, there will be examples when the basic SAGE relaxation doesn't produce a tight bound. If you DO add integrality constraints on ``v``, I'm not sure if the optimal objective of a mixed-integer SAGE relaxation would produce a tight bound; it would be very neat if one could prove that the resulting bound was always tight.

## Approach 3: intervene in branch-and-bound manually.

Some advanced features of mixed-integer solvers (like cutting plane generation) might actually, seriously rely on the fact that variables are taking *integer* values. However, the core of most mixed-integer solvers is simply an intelligent application of branch-and-bound to LP relaxations of the given problem.

Right now those solvers would want to check if ``y`` was an integer. If it wasn't, they would branch: create two problems with ``y <= np.floor(y.value)`` and ``np.ceil(y.value) <= y``. The idea is that ``low_branch = np.floor(y.value)`` and ``high_branch = np.ceil(y.value)`` are consecutive integers, and so the open interval ``low_branch < y < high_branch`` can be excluded from the search space without loss of generality.

This branching routine can easily be changed to handle ``y`` belonging to any monotonically increasing sequence of values: even an infinite such sequence! In your context you want ``x = exp(y)`` to take a positive integer value. So when branching, you do the following:
* compute  ``val = exp(y)``
* if ``val`` is an integer (up to some tolerance), then the integrality constraint was satisfied by sheer luck, and you can return the solution.
* if ``val`` is not an integer, then compute ``exp_low_branch  = np.floor(val)`` and ``exp_high_branch = np.ceil(val)``. Proceed by branching ``y <= np.log(exp_low_branch)`` and ``np.log(exp_high_branch) <= y``.

This approach is guaranteed to converge to an optimal solution, as long as the feasible set for ``x`` is bounded. Note however that you don't need to know the bounds on ``x`` ahead of time.

The problem with this approach is that you really need it implement it in the solver for decent speed. @erling-d-andersen this is perhaps something to consider. Since one of MOSEK's competitive advantages is its geometric-programming capabilities (by way of the exponential cone), commercial users might benefit from being able to specify an "exp-integer" domain. From a mathematical perspective the added feature is very simple. Although when implementing in C I realize this might be messy. If you wanted to have it feel less like a hack and more like a serious feature, you could consider defining discrete domains with respect to any strictly monotonic function. So users could define "exp-integer", "log-integer", "sqrt-integer", "squared-integer" variables, etc...

@bqpd @1ozturkbe assuming MOSEK doesn't add the above support anytime soon, you can try to manage branch and bound on your own (i.e. within python). There are existing python libraries that allow black-box branch-and-bound, so you could make calls to MOSEK (or CVXOPT or whatever else), decide how to branch, and provide necessary data to the branch-and-bound manager. But as I mentioned earlier- this will be slow. It's probably only realistic for small problems, or medium sized problems with a (very) small number of integer variables. It might be good to prototype in CVPXY with "Disciplined Parametric Programming" before modifying GPKit in any way. The idea is that you should see what convergence of the branch-and-bound schemes look like (exclusively in terms of overall solver runtime, not problem generation time) before considering a manual branch-and-bound scheme within GPKit.

**Comment by whoburg** [comment] 2020-02-06 02:21
@rileyjmurray  that's a fantastic rundown of options. Thanks for spending the time on a super clear writeup. Love the `logic_cons` idea.

I'm interested in thinking through the modeling implications of various options. There are several types of constraint a engineer/modeler might want to encode using integer variables (counting an  integer number of some part [optionally 0]; a yes/no option; a logical OR constraint; a GP analogue of a knapsack constraint; piecewise constraints or compound alternatives; others).

Do you think allowing posynomial variables to take on the value 0 (-infinity in logspace) makes things much much harder? I could imagine a crude hacky algorithm that assigns some large negative number (in logspace) to represent 0, but not sure if it would remain well-conditioned for all problems. There are obvious modeling benefits to allowing 0 in posynomial variables, e.g. representing an optional component.

By the way, probably obvious to everyone on this threat, but Stephen Boyd's 2005 paper "A tutorial on geometric programming" does mention mixed integer GP. It doesn't go into detail on the implementations but alludes to solving via branch and bound.

**Comment by rileyjmurray** [comment] 2020-02-07 19:48
@whoburg glad to hear the ideas were useful.

Regarding modeling implications, the starting point is to look at modeling tricks in mixed-integer linear programs. There are many standard recipes there to describe logical constraints. The issue is that MILP modeling assumes linear equations and linear inequalities are permitted, while the same cannot be said for GP modeling. So one could start by finding a list of MILP modeling tricks, and then figuring out which ones have MIGP analogs. Naturally one would also want to find some constraint types which might be natural in MIGP, but awkward or impossible in MILP. Finding such constraints would take some time, effort, and creativity.

Regarding posynomials taking on the value zero: the large negative number is perhaps the only solution in the short term. Supposing that we treat``exp(-20)`` as effectively zero, we could require ``y in {-20, log(1), log(2), log(3)}`` to say that ``x = exp(y)`` takes a value in``{exp(-20), 1, 2, 3}``. Such an approach will likely result in optimal solutions with very large norms. Also, the solver might try to compensate for one variable taking on a very-negative value by another variable taking on a very-positive value, so the mixed-integer logic might not be enforced as you expect. Separately, my experience is that large-norm solutions (e.g. norms ``>= 1e7``) are the a key point where solvers fail.

As to the mention of MIGP in Boyd's survey paper: I'm can't be certain of what he was envisioning, but my guess is a solver-level version of "Approach 3" in my earlier comment.

**Comment by whoburg** [comment] 2020-02-08 16:38
@rileyjmurray completely agree on looking at MILP modeling tricks for inspiration. My favorite reference on the topic is chapter 9 of this book: http://web.mit.edu/15.053/www/AMP.htm, but if anyone knows of other good sources please share.

One question @rileyjmurray -- why would the optimal solutions have very large norms if y is forced to be in e.g. `{-20, 0, log(2), log(3)}`? You're saying the non-integer-constrained portion of the solution will blow up?

**Comment by erling-d-andersen** [comment] 2020-02-18 06:47
All I can say is we will support mixed-integer conic optimization as is currently implemented. The only major feature we are going add to is disjunktive constraints in the forseeable future.  Maybe more cone types such as the n dimensional power cone will also appear.

**Comment by 1ozturkbe** [comment] 2020-02-18 12:27
@rileyjmurray I hadn't noticed until now but I think there is a small error with your improved b&b constraint in approach 1. 
```
logic_cons = [z[i+1] <= z[i] for i in range(z.size-1)] + [sum(z) <= 1]
all_cons = logic_cons + [y == L[0] + d @ z]
```
sum(z) <= 1 is incorrect, and should be removed. In either case, I think this is definitely an improved formulation for doing a non-signomial branch and bound.

**Comment by rileyjmurray** [comment] 2020-02-23 01:25
@whoburg as to my remark about large-norm solutions, it might not end up being a problem. But yes, I do have a concern that something like ``y`` with ``log(y) == -20`` might force another continuous variable ``x`` to be much larger than expected (e.g. ``log(x) >= 20``) in order to compensate. 

@1ozturkbe yup! Looks like the ``sum(z) <= 1`` was indeed an error.

**Closed** 2021-03-21 21:18 UTC
Labels: design discussion
