### ISSUE TITLE
process_solution error with sweeps

### ISSUE THREAD

**Issue by mjburton11** [convexengineering/gpkit#911] opened 2016-09-24 23:12 UTC
I have been getting this error when I tried sweeping with process result.  Unsure, if this is an error of how I am implement `process_solution` or a problem with the method itself:

``` python
  File "/Users/mjburton11/anaconda/lib/python2.7/site-packages/gpkit/constraints/set.py", line 287, in process_solution
    constraint.process_solution(sol)
  File "/Users/mjburton11/anaconda/lib/python2.7/site-packages/gpkit/constraints/tight.py", line 24, in process_solution
    leftsubbed = constraint.left.sub(variables).value
  File "/Users/mjburton11/anaconda/lib/python2.7/site-packages/gpkit/nomials/nomial_math.py", line 215, in sub
    _, exps, cs, _ = substitution(self, substitutions)
  File "/Users/mjburton11/anaconda/lib/python2.7/site-packages/gpkit/nomials/substitution.py", line 148, in substitution
    if sub != 0:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

This is my `process_solution` method

``` python
    def process_solution(self, sol):

        super(Climb, self).process_solution(sol)
        Vstall = ((sol("MTOW")*2/sol(self.slf["\\rho"][0])/
                   sol("S")/1.5)**0.5).to("m/s")
        Vland = ((sol("W_{zfw}")*2/sol(self.slf["\\rho"][0])/
                  sol("S")/1.5)**0.5).to("m/s")
        print "Stall speed at bottom of climb is: %0.3f [%s]" % \
                (Vstall.magnitude, Vstall.units)
        print "Landing speed is : %0.3f [%s]" % (Vland.magnitude, Vland.units)

```

**Comment by bqpd** [comment] 2016-09-26 18:15
*clippy voice* It looks like you're trying to substitute an array for a value

try:
```python
    def process_solution(self, sol):
        super(Climb, self).process_solution(sol)
        Vstall = sol((self["MTOW"]*2/self.slf["\\rho"][0]/
                   self["S"]/1.5)**0.5).to("m/s")
        print "Stall speed at bottom of climb is: %0.3f [%s]" % \
                (Vstall.magnitude, Vstall.units)
```

and check that `((self["MTOW"]*2/self.slf["\\rho"][0]/self["S"]/1.5)**0.5)` is the right monomial.

(this is quite possibly not what's causing the bug, but it is best practice)

**Comment by bqpd** [comment] 2016-10-06 18:55
@mjburton11, do you want this to print out for every solve in the sweep?

**Comment by bqpd** [comment] 2016-10-06 19:18
@mjburton11, could you check this is fixed by #920?

**Comment by whoburg** [comment] 2016-12-03 16:31
do we have a unit test for this?

**Comment by bqpd** [comment] 2016-12-03 18:33
It's not a bug in the current master, it was a bug in the change from `process_result` to `process_solution`. But overall, we don't have a test for sweeps of a TightConstraintSet, and one should be introduced when this issue is fixed.

**Closed** 2017-10-19 22:47 UTC
Labels: bug
