### ISSUE TITLE
clarify infeasibility warnings

### ISSUE THREAD

**Issue by mayork** [convexengineering/gpkit#753] opened 2016-06-29 20:28 UTC
I haven't seen these warnings before. These first two are thrown mid solve. Not sure if that indicates anything specific, or if the model is just bad. I was thinking it means a variable might be going unbounded to infinity so I ran with the bounded debugging tool. Seemed to stop the warning, but I wanted to double check this was reasonable.

```
Warning (from warnings module):
  File "c:\users\mayork\documents\github\gpkit\gpkit\nomials\substitution.py", line 147
    mag(cs_)[i] *= sub**x
RuntimeWarning: overflow encountered in double_scalars

Warning (from warnings module):
  File "C:\Python27\lib\site-packages\pint\quantity.py", line 715
    magnitude = magnitude_op(new_self._magnitude, other._magnitude)
RuntimeWarning: invalid value encountered in double_scalars
```

this warning is given when the solve terminates. I suspect it's similar to infeasible but I'm not 100% sure. 

```
Traceback (most recent call last):
  File "C:\Users\mayork\Documents\GitHub\gpkit-models\gpkitmodels\aircraft\engine.py", line 257, in <module>
    bounds = engineOffD.determine_unbounded_variables(engineOffD,verbosity=4)
  File "C:\Users\mayork\Documents\GitHub\gpkit-models\gpkitmodels\aircraft\engine.py", line 164, in determine_unbounded_variables
    sol = m.localsolve(solver, verbosity, **kwargs)
  File "c:\users\mayork\documents\github\gpkit\gpkit\constraints\prog_factories.py", line 80, in solvefn
    result = solvefn(solver, verbosity-1, *args, **kwargs)
  File "c:\users\mayork\documents\github\gpkit\gpkit\constraints\signomial_program.py", line 112, in localsolve
    result = nearest_feasible.solve(solver, verbosity=verbosity-1)
  File "c:\users\mayork\documents\github\gpkit\gpkit\geometric_program.py", line 211, in solve
    nu=solver_out["nu"], la=solver_out["la"])
  File "c:\users\mayork\documents\github\gpkit\gpkit\geometric_program.py", line 359, in check_solution
    primal_exp_vals[mi].sum())
RuntimeWarning: Primal solution violates constraint: 1.00004530548 is greater than 1.
```

**Comment by bqpd** [comment] 2016-06-29 22:10
Yeah, looks like a dual-infeasible model?

**Comment by mayork** [comment] 2016-06-29 22:36
It certainly could be dual infeasible, but cvxopt is not telling me that. I tagged you and woody in a comment to see if you could run a slightly tweaked version of the model giving this error in MOSEK, I wouldn't be surprised if MOSEK returned dual infeasible.

**Comment by whoburg** [comment] 2016-07-02 17:11
the first two `double_scalars` warnings aren't too user-friendly for this situation -- maybe they should be caught and a more informative exception raised.

**Comment by mayork** [comment] 2016-07-02 17:18
I'm fairly certain that the model I ran was dual feasible when it threw those errors. Interestingly I saw them yesterday as well when I substituted an incorrect value into a model. However, the solution kept going and it output a "solution". I was thinking maybe if something like an overflow warning occurs execution should stop?

**Comment by bqpd** [comment] 2016-09-08 06:14
You might have seen it in an SP solve, where it was caught and turned into a feasibility solve?

**Comment by mayork** [comment] 2016-09-08 11:00
It was an SP, it's possible everything was caught but would it print to the screen if that was the case?

**Comment by mayork** [comment] 2016-09-08 11:02
My main reason for posting this was, if I was a new user, and solved a GP and got overflow errors I think I would be concerned that the GP iteration continued after throwing an overflow error.

**Comment by bqpd** [comment] 2016-09-08 15:16
Yeah, you're right that it wouldn't print in that case.

**Comment by pgkirsch** [comment] 2016-10-06 03:37
I just got the same "Primal solution violates constraint: 1.0000105916 is greater than 1." warning. Is there any way we can add a tolerance to `check_solution` so it lets things like this slip. I am confident that the change I made that led to this warning did not cause the model to become dual infeasible.

**Comment by bqpd** [comment] 2016-10-06 03:46
@whoburg

**Comment by whoburg** [comment] 2016-10-10 23:04
I think the right way to implement this is to expose the `tol=1e-5` kwarg of `check_solution` in `solve` and `localsolve` methods. It will be important to get the naming right because there are several tolerances that may be relevent, e.g.:

 - GP solution check tolerances (local to GPkit, post-solution)
 - GP solver tolerances (passed to solvers)
 - SP heuristic tolerances

**Comment by bqpd** [comment] 2016-10-10 23:06
We seem to be tolerant to a diversity of tolerances. Metatolerant.

**Comment by pgkirsch** [comment] 2016-10-11 16:11
a perhaps-interesting observation: Just got the same error for another model, but then changing a constraint from inequality to equality made it go away.

**Comment by pgkirsch** [comment] 2016-10-14 18:22
I also think the default value for `tol` should be larger. If I understand correctly, this check_solution is meant to catch significant errors, and these ~1E-4 violations are kind of a nuisance.

**Comment by bqpd** [comment] 2016-10-25 02:01
I completely agree. Could we change this tolerance to 1e-3, even?

**Comment by pgkirsch** [comment] 2016-10-25 02:15
I'm guessing you're asking @whoburg, but that would be fine with me.

**Comment by whoburg** [comment] 2016-10-25 15:17
BLUF: I think solution_check should match the tolerances used by the solver.

The solution check method is a final check to make sure that the solution found by the solver is primal and dual feasible (and that the cost matches the reported cost).

If the error in question is raised, the solution returned by the solver is NOT feasible. Solvers do have a small tolerance on feasibility, hence so do we. But turning this down below the tolerance used by the solver seems dangerous. The point of the method is to promote some debugging effort when things aren't going to plan. And when a solution violates the solver's own tolerance setting, that warrants some attention.

In @pgkirsch's case where he saw `1.0000105916 is greater than 1`, I'm pretty sure the solver tolerance is 1e-5 (this can be set for both solvers, though GPkit does not currently expose the option). I don't know why this solution was allowed by the solver. Maybe the definition of error is slightly different than in our check_solution. We could add a small 10% fudge to account for this, e.g. make our tolerance 1.1 times the tolerance used by the solver.

But I don't like arbitrarily making our tolerance 100 times larger -- we'd be likely to lose track of what's causing these errors.

My proposal is that we expose the solver tolerance as an optional kwarg to `solve` and `localsolve`, and infer the `solutioncheck` tolerance from those values, possibly with a small ~10% slop.

**Comment by whoburg** [comment] 2016-10-25 15:26
Follow up: @pgkirsch was this cvxopt? The `feastol` default for cvxopt is 1e-7, so the violation having magnitude ~1e-5 is super worthy of debugging and bug reporting.

**Comment by pgkirsch** [comment] 2016-10-25 21:36
Yes this is cvxopt. I get this sort of error with surprising frequency (weekly, sometimes daily basis).

From a debugging point of view, it might be helpful to make the runtime warning a little more verbose (a la TightConstraintSet) so we can know if there is a repeat offending constraint, and if there is some underlying reason why certain constraints are prone to this sort of error.

**Comment by bqpd** [comment] 2016-11-30 18:36
@whoburg, @pgkirsch, what's the status of this.

**Comment by whoburg** [comment] 2016-11-30 18:48
I think we're discussing two separate but parallel lines of inquiry/debugging:

1. How does this error get raised in the first place? Note that when things like `Primal solution violates constraint: 1.0000105916 is greater than 1.` are printed, the solver is returning a PRIMAL_AND_DUAL_FEASIBLE solution that (presumably) satisfies its own tolerances but not those of gpkit.solution_check. This makes me really want us to dig in and understand where the tolerances disagree (as opposed to blindly making the solution_check tolerances looser). A straightforward fix would be to set our tolerances for each solver based on that solver's default and an optional kwarg to solve(). This presumes that there are no solver errors / violations of tolerances within the solver.

2. Is there a specific qualitative type of model or constraint that causes this behavior to occur? That's certainly an interesting question.

My position is that item 1. is much more well-defined and straightforward to work on; it feels like the right first step to me before pursuing 2., which seems harder and more open-ended.

Definitely feel the ticket needs to remain open (we even link to it from the docs here: http://gpkit.readthedocs.io/en/latest/debugging.html#potential-errors-and-warnings, suggesting that users let us know if they encounter the issue).

**Comment by whoburg** [comment] 2016-11-30 18:50
Could really use some concrete examples of this occurring -- if anyone sees this error on a public model please post commit hashes and instructions to reproduce.

**Comment by pgkirsch** [comment] 2016-12-08 01:17
Sorry for the slow response @bqpd. Coincidentally, this just started cropping up again in my work. Wish I could share code, because it is super frustrating. This probably isn't especially useful information, but having different substitution values can either trigger or resolve this error (e.g. along a sweep, some instances return this error). It seems like a "lack of pressure" thing to me. I maintain that having GPkit say which constraint is the offender could be helpful.

**Comment by whoburg** [comment] 2016-12-08 14:49
@pgkirsch, two questions

1. what's `python -c "import cvxopt.info; print cvxopt.info.version"` for you?

2. next time this happens, could you please turn up the verbosity and give us the cvxopt iteration printout? (example below). I want us to debug the tolerances -- as far as I can tell cvxopt's termination criteria require `pres <= FEASTOL and dres <= FEASTOL` (or `iters == MAXITERS`), and FEASTOL defaults to 1e-7, so I'm confused how this is happening.

example high verbosity printout
```
Using solver 'cvxopt'
Solving for 9 variables.
     pcost       dcost       gap    pres   dres
 0:  0.0000e+00 -1.0751e+01  9e+00  1e+00  1e+00
 1:  6.0152e+00  5.6008e+00  9e-01  1e-01  1e-01
 2:  5.9276e+00  5.6183e+00  6e-01  7e-02  8e-02
 3:  5.9134e+00  5.7469e+00  4e-01  4e-02  5e-02
 4:  5.8012e+00  5.7638e+00  1e-01  2e-02  2e-02
 5:  5.7867e+00  5.7863e+00  2e-02  9e-04  5e-03
 6:  5.7868e+00  5.7867e+00  1e-03  6e-05  4e-04
 7:  5.7867e+00  5.7867e+00  2e-05  8e-07  6e-06
 8:  5.7867e+00  5.7867e+00  2e-07  8e-09  6e-08
Optimal solution found.
Solving took 0.00924 seconds.
result packing took 19% of solve time
solution checking took 5.2% of solve time
Sweeping took 0.0596 seconds.
```

**Comment by pgkirsch** [comment] 2017-02-14 19:02
@whoburg I had been operating with 1e-4 for the last few months. Returning to 1e-5 now gave me the same error for one of my model variants. As requested:

1.
```python
In [6]: print cvxopt.info.version
1.1.8
```

2. 
```python
Using solver 'cvxopt'
Solving for 174 variables.
     pcost       dcost       gap    pres   dres
 0:  0.0000e+00  3.2404e+01  2e+02  1e+00  1e+00
 1:  1.4662e-01 -6.7261e+00  2e+02  7e-01  7e-01
 2:  9.1577e-01 -2.8300e+01  1e+02  4e-01  4e-01
 3:  2.7588e+00 -2.8261e+01  7e+01  2e-01  2e-01
 4:  1.6081e+00 -9.9038e+00  2e+01  3e-02  6e-02
 5: -3.4261e-01 -4.8605e+00  6e+00  7e-03  2e-02
 6: -1.4859e+00 -3.2911e+00  2e+00  2e-03  7e-03
 7: -2.0797e+00 -2.8256e+00  9e-01  1e-03  3e-03
 8: -2.3812e+00 -2.6451e+00  3e-01  7e-04  1e-03
 9: -2.4938e+00 -2.6206e+00  1e-01  4e-04  3e-04
10: -2.5626e+00 -2.5954e+00  4e-02  3e-04  8e-05
11: -2.5850e+00 -2.5899e+00  7e-03  2e-04  2e-05
12: -2.5879e+00 -2.5894e+00  2e-03  7e-05  6e-06
13: -2.5891e+00 -2.5891e+00  1e-04  7e-06  1e-06
14: -2.5891e+00 -2.5891e+00  6e-06  8e-07  3e-07
15: -2.5891e+00 -2.5891e+00  3e-07  9e-08  3e-08
Optimal solution found.
Solving took 0.835 seconds.
result packing took 2.7% of solve time
---------------------------------------------------------------------------
RuntimeWarning                            Traceback (most recent call last)
<ipython-input-4-5578c66232fb> in <module>()
----> 1 sol = hl.solve(verbosity=5)

/Users/philippe.kirschen/Documents/Optimization/gpkit/gpkit/constraints/prog_factories.pyc in solvefn(self, solver, verbosity, skipsweepfailures, *args, **kwargs)
     78         else:
     79             self.program, solvefn = genfunction(self, verbosity)
---> 80             result = solvefn(solver, verbosity, *args, **kwargs)
     81             solution.append(result)
     82         solution.program = self.program

/Users/philippe.kirschen/Documents/Optimization/gpkit/gpkit/constraints/geometric_program.pyc in solve(self, solver, verbosity, *args, **kwargs)
    184 
    185         self.check_solution(self.result["cost"], solver_out['primal'],
--> 186                             nu=solver_out["nu"], la=solver_out["la"])
    187         if verbosity > 1:
    188             print("solution checking took %.2g%% of solve time" %

/Users/philippe.kirschen/Documents/Optimization/gpkit/gpkit/constraints/geometric_program.pyc in check_solution(self, cost, primal, nu, la, tol, abstol)
    303                 raise RuntimeWarning("Primal solution violates constraint:"
    304                                      " %s is greater than 1." %
--> 305                                      primal_exp_vals[mi].sum())
    306         # check dual sol
    307         # note: follows dual formulation in section 3.1 of

RuntimeWarning: Primal solution violates constraint: 1.00001091203 is greater than 1.
```

**Comment by pgkirsch** [comment] 2017-02-14 19:04
Are we still ok with exposing `tol` to the `solve()` method?

**Comment by bqpd** [comment] 2017-02-14 21:56
Potentially! For now we support just printing such warnings, see https://github.com/hoburg/d8/issues/17#issuecomment-274136575

**Comment by whoburg** [comment] 2017-02-15 14:08
Would like to see what @pgkirsch's example does once https://github.com/hoburg/gpkit/pull/1017 is merged

**Comment by bqpd** [comment] 2017-02-15 14:39
He could test on that branch even before then!

**Closed** 2017-10-19 22:32 UTC
